option solver knitroampl;
#option ipopt_options 'max_cpu_time=120 max_iter=1000 tol=1e-6';

model belief_update_test.mod;
data belief_update_test.dat;
solve;

printf "%f\n",_solve_time > time.txt;


#display value > value.txt;
#display coverage > defender_strat.txt;
#display attack > attacker_strat.txt;
#display coverageAttacker > coverage_attacker.txt;
printf "%f\n", objective > objective.txt;


#display objective > objective.txt;
#printf "%f\n",v[1] > value.txt;
#printf "" > defender_strat.txt;
#printf "" > attacker_strat.txt;

#for {i in 1..T} {
#	for {j in 1..T} {
#	        if j = T then {
#			printf "%f\n",c[i,j] >> defender_strat.txt;
#               }
#		else {
#			printf "%f ",c[i,j] >> defender_strat.txt;
#                }
#        }
#}

#for {i in 1..T} {
#	for {j in 1..T} {
#		if j = T then {
#			printf "%d\n",a[i,j] >> attacker_strat.txt;
#		}
#                else {
#                      	printf "%d ",a[i,j] >> attacker_strat.txt;
#		}
#	}
#}
