option solver knitroampl;
option presolve_eps 1.0e-6;
#option ipopt_options 'max_cpu_time=120 max_iter=1000 tol=1e-6';

model belief_update_test_convex.mod;
data belief_update_test.dat;
solve;

printf "%f\n",_solve_time > time.txt;

#set tempobjective := sum{o in observations}(preProb[o]*(coverage[1]^Ospace[o,1] * coverage[2]^Ospace[o,2])*d[o]);


param sumobj;
param temp {1..observationSpace};

let sumobj := 0;

for {i in 1..observationSpace} {
	let temp[i] := 1;
	for {j in 1..nTargets} {
		let temp[i] := temp[i] * coverage[j]^Ospace[i,j];
	}
	let temp[i] := temp[i]*preProb[i]*d[i];
	let sumobj := sumobj + temp[i];
}

printf "%f\n", sumobj > objective.txt;
#display sumobj;


#set tempobjective = sum{o in 1..observationSpace}preProb[o];

#display tempobjective;

#display value > value.txt;
#display coverage > defender_strat.txt;
#display attack > attacker_strat.txt;
#display coverageAttacker > coverage_attacker.txt;
#printf "%f\n", objective > objective.txt;

#printf "%f\n",v[1] > value.txt;
#printf "" > defender_strat.txt;
#printf "" > attacker_strat.txt;

#for {i in 1..T} {
#	for {j in 1..T} {
#	        if j = T then {
#			printf "%f\n",c[i,j] >> defender_strat.txt;
#               }
#		else {
#			printf "%f ",c[i,j] >> defender_strat.txt;
#                }
#        }
#}

#for {i in 1..T} {
#	for {j in 1..T} {
#		if j = T then {
#			printf "%d\n",a[i,j] >> attacker_strat.txt;
#		}
#                else {
#                      	printf "%d ",a[i,j] >> attacker_strat.txt;
#		}
#	}
#}
